### ISSUE TITLE
Generate validator for type/interface

### ISSUE THREAD

**Issue by andrenarchy** [paperhive/fefe#5]
Given a type/interface, it would be great if fefe could construct a runtime validator for that type.

Example:
```typescript
import { fromType } from 'fefe'

interface Person {
  name: string
  birthday?: Date
}

const validator = fromType(Person)
```
`validator` then should be of type `(value: unknown) => Person` and behave like
```
import { object, string, date } from 'fefe'
const explicitValidator = object({ 
  name: string(),
  birthdate: { validator: date(), optional: true }
})
``` 
which is tedious to type and error-prone.

This feature would make validating user input significantly easier, e.g. in REST APIs.

**Comment by andrenarchy** [comment]
Note: I assume this requires compile-time support since types are stripped during compilation. Feel free to add ideas here! :)

**Comment by andrenarchy** [comment]
Just discussed with @andywer: he thinks it'd clutter fefe up too much and you should rather create the type from the fefe definition (e.g., with `type Person = ReturnType<typeof validatePerson>`). I agree and if you have a type defined somewhere explicitly and need a validator you can choose to either create the type from the fefe validator or to just leave it – TypeScript will tell you if the types don't match.

**Comment by andywer** [comment]
Wow, that one was discarded quickly! Much lean, much agile 😅
