### ISSUE TITLE
Add default() helper

### ISSUE THREAD

**Issue by andrenarchy** [paperhive/fefe#7]
Similar to the `optional()` helper (see #6), it'd be great if we could also use a `default()` helper for generating object validation options like this one
```
  id: {
    validator: string(),
    default: () => generateUuid()
  }
```
via something like
```
id: default(string(), () => generateUuid())
```

However, default is a keyword in JS so we need to find another name for exporting such a helper. Any ideas? @andywer

**Comment by andywer** [comment]
Tricky... Can't think of anything better than `defaultTo` right now either. Will keep thinking 😉

**Comment by andrenarchy** [comment]
`defaultTo` is great, I'll do that, thanks!
